### ISSUE TITLE
Nenv setup in `~/.zshrc` requires that you put `eval "$(nenv init -)"` after `export PATH="$HOME/.nenv/bin:$PATH"`

### ISSUE THREAD

**Issue by jasonfb** [ryuone/nenv#21]
unlike rbenv, when creating the `~/.zshrc` file, the `eval "$(nenv init -)"` must come after the export PATH=

**DOES NOT WORK**
```
eval "$(rbenv init - zsh)"
eval "$(nenv init -)"
export PATH="$HOME/.nenv/bin:$PATH"
```
When I do this, the nenv seems not to be correctly loaded when I open new terminal window. For one thing, when I open Terminal, I get this message

![Monosnap jason — -zsh — 80×24 2022-09-21 10-52-44](https://user-images.githubusercontent.com/59002/191537914-593834af-10b8-472d-abf7-bee4671def77.png)

Secondly, `nenv` doesn't respond correctly (although it does seem to exist here)

![Monosnap jason — -zsh — 80×24 2022-09-21 10-54-08](https://user-images.githubusercontent.com/59002/191538164-e74ee49a-c737-4c2e-8fce-380c67baf783.png)

WORKS: put the `eval "$(nenv init -)"` after the `export PATH="$HOME/.nenv/bin:$PATH"`
```
eval "$(rbenv init - zsh)"
export PATH="$HOME/.nenv/bin:$PATH"
eval "$(nenv init -)"
```

**Comment by jasonfb** [comment]
fixed with documentation : https://github.com/ryuone/nenv/pull/22

**Comment by ryuone** [comment]
#22 Merged.
